### ISSUE TITLE
Package broken by import

### ISSUE THREAD

**Issue by jmarshall9120** [0000matteo0000/quart-login#1]
Cannot import _request_ctx_stack from quart.  This import prevents the import of the entire package:

```
Traceback (most recent call last):
  File "M:\source\bandz-padline-webserver\main.py", line 6, in <module>
    import quart_login
  File "M:\source\bandz-padline-webserver\venv\lib\site-packages\quart_login\__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "M:\source\bandz-padline-webserver\venv\lib\site-packages\quart_login\login_manager.py", line 5, in <module>
    from quart import _request_ctx_stack
ImportError: cannot import name '_request_ctx_stack' from 'quart' (M:\source\bandz-padline-webserver\venv\lib\site-packages\quart\__init__.py)
```

The proper import at this time:
```
from quart.globals import _request_ctx_stack
```

Also, I don't think you can `_request_ctx_stack`  on the general import of quart_login.  I think the server and context have to exist for `_request_ctx_stack` to load

**Comment by anselal** [comment]
I get the same error

**Comment by rouge-humanity** [comment]
```from quart import _request_ctx_stack```
this method is not in quart. There is a ctx module, but nothing that relates to the import. Additionally, I cannot find any history of the above mentioned module.

**Comment by lennertcl** [comment]
Same issue here, is this package even still a thing? Also having issues using flask patch with flask_login

**Comment by callowaysutton** [comment]
Same issue, no fix in sight...
